<?php
$type = "admin";
return [
    'validation' => [
        'user' => $type.'/validation/user.',
        'address'=>$type.'/validation/address.',
        'category'=>$type.'/validation/category.',
        'category_specification'=>$type.'/validation/category_specification.',
        'claim_book'=>$type.'/validation/claim_book.',
        'contact'=>$type.'/validation/contact.',
        'currency'=>$type.'/validation/currency.',
        'event'=>$type.'/validation/event.',
        'event_invitation'=>$type.'/validation/event_invitation.',
        'list_products_event'=>$type.'/validation/list_products_event.',
        'order'=>$type.'/validation/order.',
        'order_detail'=>$type.'/validation/order_detail.',
        'parameter'=>$type.'/validation/parameter.',
        'product'=>$type.'/validation/product.',
        'product_group'=>$type.'/validation/product_group.',
        'product_price'=>$type.'/validation/product_price.',
        'product_specification'=>$type.'/validation/product_specification.',
        'shipping_price'=>$type.'/validation/shipping_price.',
        'specification'=>$type.'/validation/specification.',
        'suscriber'=>$type.'/validation/suscriber.',
        'type'=> $type.'/validation/type.',
        'type-group'=>$type.'/validation/type-group.',
        'ubication'=>$type.'/validation/ubication.',
        'user'=>$type.'/validation/user.',
        'electronic_billing_sale'=>$type.'/validation/electronic_billing_sale.',
        'ldproducts'=>$type.'/validation/ld_products.',
        'tracing'=>$type.'/validation/tracing.',
        'discount'=>$type.'/validation/discount',
    ],
];
